### ISSUE TITLE
Add option for oblong mounting holes instead of 3mm circles

### ISSUE THREAD

**Issue by benjiao** [benjiaomodular/EuroPanelMaker#1]

**Comment by benjiao** [comment]
Thanks! I forgot to close this issue. I don't see any downside to this so it's now the default for everything above 1HP. 

![Screenshot from 2023-05-19 20-25-03](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/b271ae7c-ef15-4a67-8b14-74d0435f6212)

**Comment by dromer** [comment]
nice!
