### ISSUE TITLE
Jacks don't render

### ISSUE THREAD

**Issue by Efroymson** [benjiaomodular/EuroPanelMaker#20]
I am working on a panel for this format, and I want to put some jacks in, I am using jacks_mm but I notice that I don't see any holes being generated in the CV Mixer example either, only the pots and the LED show up.

**Comment by slashinfty** [comment]
Can you share your code for them?

**Comment by Efroymson** [comment]
include <../EuroPanelMaker/panel.scad>

hp = 26;
title = "MCU";
text_depth = 1.6;
title_font_size = 3.8;
margin = 3;

pots_mm = [
    [84, 61, "", -90],
    [100, 61, "", -90],
    [1166, 61, "", -90],
    [60, 86, "", -90],
];

//leds = [[1, 49, 3]];

jacks_mm = [
    [15, 21, "1", -90],
    [30, 21, "2", -90],
    [70, 21, "3", -90],
    [85, 21, "4", -90],
    [105, 21, "L", -90],
    [120, 21, "R", -90]
];

panel_flipped = true;
generatePanel();

**Comment by slashinfty** [comment]
From the documentation, jacks should be `[x (in HP column), y (mm), label, size, rotation (degrees)]`, so you should have `"35mm"` between the label and the rotation. Additionally, -90 can be accomplished with 270.

```
jacks_mm = [
    [15, 21, "1", "35mm", 270],
    [30, 21, "2", "35mm", 270],
    [70, 21, "3", "35mm", 270],
    [85, 21, "4", "35mm", 270],
    [105, 21, "L", "35mm", 270],
    [120, 21, "R", "35mm", 270]
];
```

**Comment by slashinfty** [comment]
Did this solve your issue?

**Comment by Efroymson** [comment]
It did! I might have more questions as I work through the boards I’m
designing, I definitely appreciate your responsiveness.

**Comment by benjiao** [comment]
Thanks @slashinfty @Efroymson! Closing this issue for now.

@Efroymson we have a Discord in case you need more help. 😊 https://discord.gg/5nfxWf85
