### ISSUE TITLE
Add support for 1.3inch OLED (with generic rectangle?)

### ISSUE THREAD

**Issue by Efroymson** [benjiaomodular/EuroPanelMaker#22]
I can probably figure out how to put a rectangular cut in the right place, so this is not essential, but I have some of these:
https://www.waveshare.com/1.3inch-oled-b.htm
and my front panel will need to accommodate them.  These would probably best be located by a corner, rather than centered.

**Comment by benjiao** [comment]
I've actually just added a way to do rectangular holes, I forgot to note it in the docs. 😅

https://github.com/benjiaomodular/EuroPanelMaker/blob/main/examples/benjiaomodular/europi-handwired.scad#L49-L51

```
rectangular_holes = [
    [<x>, <y>, <inner_width>, <inner_height>, <outer_width>, <outer_height>]
];
```
![Screenshot from 2023-08-15 01-22-01](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/a2095009-6b22-409a-9bcb-a6bd25dce20e)

![Screenshot from 2023-08-15 01-19-20](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/bd9615ea-4cbd-4a49-a5cb-ebec8bc5efed)

Inner and outer dimensions lets us recess the screens into the panel a bit. You'd still have to use hot glue to hold it in place. I've already use it twice. It isn't perfect, but it works!

![C0102051](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/8096ecbc-abd4-41b4-80bf-f9f23083d17f)

![C0102036](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/feffde0a-9e5b-4d85-9fc3-7264c8153323)

**Comment by Efroymson** [comment]
Is there a version of this with mm?

**Comment by benjiao** [comment]
> Is there a version of this with mm?

Yup! Just merged some changes with mm support. Just use `rectangular_holes_mm` instead and the `x` parameter will be in mm. :)
