### ISSUE TITLE
Request for countersunk holes

### ISSUE THREAD

**Issue by Efroymson** [benjiaomodular/EuroPanelMaker#25]
I am using the led part for a variety of other purposes, including pushbuttons:
https://www.digikey.com/en/products/detail/e-switch/TL1105SPF250Q/271559
with caps:
https://www.digikey.com/en/products/detail/e-switch/1RBLK/271579

That seems to work fine if I simply set the hole size to 5mm.

I also use it to make round 3mm holes for hex spacers like these:
https://www.amazon.com/dp/B08DMSNB8X?psc=1&ref=ppx_yo2ov_dt_b_product_details
but it would be handy if the holes could be countersunk.  Is that possible?  The plastic is too think for the standard screws to reach all the way through, and countersinking would also make them flush

**Comment by benjiao** [comment]
Good suggestion! I also have these standoffs in stock

It'll probably make sense to countersink them from the back. That should keep the print layers from separating when pushing buttons. 

I'll try some things out. 👌

**Comment by benjiao** [comment]
Two thoughts about it:

1. It's trickier to print with overhangs. Since we print these face down, I'd try to keep the front panel flat. 
2. I was just thinking about the way layers are printed when FDM printing. Having the head of the screws supported by a middle layer adds a risk of ripping that layer off (It did happen to me in some earlier prototypes).

![Screenshot from 2023-08-31 05-13-07](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/da3a27ad-2380-4471-bd9e-31676c2572a3)

**Comment by Efroymson** [comment]
I see what you mean now.  I have never seen a part delaminate like that.  Though I am much newer to 3d printing panels than you are, I have been doing a fair amount of printing for some years.  I would suspect a printer issue if my layers could not hold up to the kinds of forces you are talking about.

I notice however that I am unlikely to have the problem listed at the end of this article, since I live in the desert:
https://all3dp.com/2/3d-print-delamination-tips-tricks-to-avoid-layer-separation/

**Comment by benjiao** [comment]
Yeah. I just prefer my designs to be more forgiving.

Not requiring people to tune their printers perfectly makes the designs more accessible.

**Comment by benjiao** [comment]
@Efroymson done! Test print works great so far. 😁

![IMG20230831102535](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/2a86b88e-414d-428f-a0ac-ee720bb89fca)
![IMG20230831102528](https://github.com/benjiaomodular/EuroPanelMaker/assets/5189714/7d9ced92-dd49-42c1-b802-df1af343cea9)
