### ISSUE TITLE
Add option to use mm instead of HP for horizontal placement

### ISSUE THREAD

**Issue by benjiao** [benjiaomodular/EuroPanelMaker#3]
This should be useful for designing panels for PCB builds

**Comment by slashinfty** [comment]
I can probably tackle this easily. Instead of adding more parameters to component definitions, what do you think about alternative declarations? Instead of `jacks = [ ]`, there's `jacks_mm = [ ]` and it does all the same work.

**Comment by benjiao** [comment]
Yup! That works. I'll check it in a bit. Thanks again, @slashinfty. 🙏

**Comment by benjiao** [comment]
Closed by #14. Thanks, @slashinfty.
